name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Solution_Name: DhanAlgoTrading.sln
      Test_Project_Path: DhanAlgoTrading.Tests/DhanAlgoTrading.Tests.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore ${{ env.Solution_Name }}
    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --no-restore --configuration Release
    - name: Test
      run: dotnet test ${{ env.Test_Project_Path }} --no-build --configuration Release
